language: ruby
rvm:
  - 2.2
script: "bundle exec rake"
gemfile:
  - Gemfile
before_script:
  - mysql -e 'create database database_cleaner_test;'
  - psql -c 'create database database_cleaner_test;' -U postgres
  - cp db/sample.config.yml db/config.yml
services:
  - redis-server
  - mongodb

before_install:
    # install Neo4j locally:
    - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - neo4j-community-$NEO4J_VERSION/bin/neo4j start
